### ISSUE TITLE
Please post

### ISSUE THREAD

**Issue by spdegabrielle** [dannypsnl/cover-badge#1]
Hi

please post on 
https://racket.discourse.group/c/show-and-tell/7

And

#show-and-tell in https://discord.gg/DBuvY2KcQ7

**Comment by dannypsnl** [comment]
- discourse: https://racket.discourse.group/t/a-tool-generating-coverage-badges/1118?u=dannypsnl
- discord: https://discord.com/channels/571040468092321801/832076990923669554/992959439567069214

Done!
